### ISSUE TITLE
`gcloud preview app` will go away

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/appengine-dart-todos#3]
The README has 2 instances of `gcloud preview app`.

For `gcloud preview app run`, please consider running the application server locally.
For `gcloud preview app deploy`, just use `gcloud app deploy`.

**Comment by arashbi** [comment]
I am not sure how to run this application.

When I try to do a `docker run ...` I got 
Unhandled exception:
Bad state: Expected docker environment variables not found.
#0      initializeAppEngine.getDockerContext (package:appengine/src/appengine_internal.dart:59:7)
#1      initializeAppEngine (package:appengine/src/appengine_internal.dart:95:33)
#2      withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:120:12)
#3      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
#4      _rootRun (dart:async/zone.dart:1150)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      runZoned (dart:async/zone.dart:1503)
#7      _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
#8      fork (package:gcloud/service_scope.dart:103:30)
#9      withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:119:10)
#10     withAppEngineServices (package:appengine/src/appengine_internal.dart:129:10)
#11     withAppEngineServices (package:appengine/appengine.dart:113:10)
#12     main (file:///app/bin/server.dart:28:3)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
